<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>Cyclotron.Graph.Sample</RootNamespace>
    <AssemblyName>Cyclotron.Graph.Sample</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <UserSecretsId>bc1efe26-725b-4b30-9011-19f26e6ee68f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cyclotron.Graph.Mail\Cyclotron.Graph.Mail.csproj" />
  </ItemGroup>

</Project>
